@extends('layouts.admin')

@section('title', 'Contract Details - Pxp3 Admin')

@section('header', 'Contract Details')

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('admin.contracts.index') }}">Contracts</a></li>
<li class="breadcrumb-item active">Details</li>
@endsection

@section('content')
<div class="row">
    <div class="col-12 mb-4">
        <div class="card rounded-5 border-0 shadow-lg">
            <div class="card-header bg-tertiary bg-opacity-10 border-0">
                <div class="d-flex justify-content-between align-items-center">
                    <h5 class="card-title mb-0 fw-bold">
                        <i class="fas fa-file-contract me-2 text-tertiary"></i>
                        Contract #{{ $contract->id }}
                    </h5>
                    <div>
                        <a href="{{ route('admin.contracts.download', $contract) }}" class="btn btn-success btn-sm rounded-pill me-2">
                            <i class="fas fa-download me-1"></i> Download
                        </a>
                        <a href="{{ route('admin.contracts.index') }}" class="btn btn-outline-secondary btn-sm rounded-pill">
                            <i class="fas fa-arrow-left me-1"></i> Back
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                @if(session('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('success') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                
                <div class="row g-4">
                    <!-- Contract Information -->
                    <div class="col-md-6">
                        <div class="p-4 rounded-4 bg-light bg-opacity-10 h-100">
                            <h6 class="fw-bold mb-4 text-tertiary">
                                <i class="fas fa-file-contract me-2"></i>
                                Contract Information
                            </h6>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Contract Name</p>
                                <p class="mb-3">{{ $contract->name }}</p>
                            </div>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Base Template</p>
                                <p class="mb-3">{{ $contract->template->name }}</p>
                            </div>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">File Format</p>
                                <p class="mb-3">
                                    <span class="badge {{ $contract->file_type == 'pdf' ? 'bg-danger' : 'bg-primary' }} rounded-pill px-3 py-2">
                                        {{ strtoupper($contract->file_type) }}
                                    </span>
                                </p>
                            </div>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Generated on</p>
                                <p class="mb-3">{{ $contract->created_at->format('M d, Y H:i') }}</p>
                            </div>
                            
                            <div class="mb-0">
                                <p class="mb-1 text-muted fw-bold small">Generated by</p>
                                <p class="mb-0">{{ $contract->creator->name ?? 'User not found' }}</p>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Client Information -->
                    <div class="col-md-6">
                        <div class="p-4 rounded-4 bg-light bg-opacity-10 h-100">
                            <h6 class="fw-bold mb-4 text-info">
                                <i class="fas fa-user-tie me-2"></i>
                                Client Information
                            </h6>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Client Name</p>
                                <p class="mb-3">{{ $contract->client_name }}</p>
                            </div>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Address</p>
                                <p class="mb-3">{{ $contract->client_address }}</p>
                            </div>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Contracted Service</p>
                                <p class="mb-3">{{ $contract->service_type }}</p>
                            </div>
                            
                            <div class="mb-0">
                                <p class="mb-1 text-muted fw-bold small">Sales Representative</p>
                                <p class="mb-0">{{ $contract->sales_rep_name }}</p>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Project Details -->
                    <div class="col-md-6">
                        <div class="p-4 rounded-4 bg-light bg-opacity-10 h-100">
                            <h6 class="fw-bold mb-4 text-success">
                                <i class="fas fa-project-diagram me-2"></i>
                                Project Details
                            </h6>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Project Description</p>
                                <p class="mb-3">{{ $contract->project_description }}</p>
                            </div>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Start Date</p>
                                <p class="mb-3">{{ $contract->start_date->format('M d, Y') }}</p>
                            </div>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Delivery Date</p>
                                <p class="mb-3">{{ $contract->delivery_date->format('M d, Y') }}</p>
                            </div>
                            
                            <div class="mb-0">
                                <p class="mb-1 text-muted fw-bold small">Warranty</p>
                                <p class="mb-0">{{ $contract->warranty }}</p>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Payment Details -->
                    <div class="col-md-6">
                        <div class="p-4 rounded-4 bg-light bg-opacity-10 h-100">
                            <h6 class="fw-bold mb-4 text-warning">
                                <i class="fas fa-money-bill-wave me-2"></i>
                                Payment Details
                            </h6>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Total Value</p>
                                <p class="mb-3 fs-4 fw-bold">R$ {{ number_format($contract->total_value, 2, ',', '.') }}</p>
                            </div>
                            
                            <div class="mb-3">
                                <p class="mb-1 text-muted fw-bold small">Payment Method</p>
                                <p class="mb-3">{{ $contract->payment_method }}</p>
                            </div>
                            
                            <div class="mb-0">
                                <p class="mb-1 text-muted fw-bold small">Payment Terms</p>
                                <p class="mb-0">{{ $contract->payment_terms }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="mt-4 pt-3 border-top d-flex justify-content-center gap-2">
                    <a href="{{ route('admin.contracts.download', $contract) }}" class="btn btn-success rounded-pill">
                        <i class="fas fa-download me-2"></i> Download {{ strtoupper($contract->file_type) }}
                    </a>
                    
                    <form action="{{ route('admin.contracts.create-from-template') }}" method="GET" class="d-inline">
                        <input type="hidden" name="template_id" value="{{ $contract->template_id }}">
                        <button type="submit" class="btn btn-warning rounded-pill">
                            <i class="fas fa-sync me-2"></i> Regenerate Contract
                        </button>
                    </form>
                    
                    <a href="{{ route('admin.contracts.create') }}" class="btn btn-primary rounded-pill">
                        <i class="fas fa-plus me-2"></i> New Contract
                    </a>
                    
                    <form action="{{ route('admin.contracts.destroy', $contract) }}" method="POST" class="d-inline">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger rounded-pill" 
                                onclick="return confirm('Are you sure you want to delete this contract?')">
                            <i class="fas fa-trash me-2"></i> Delete
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.btn-sm {
    padding: 0.25rem 0.8rem;
}

.rounded-pill {
    border-radius: 50rem;
}

.rounded-4 {
    border-radius: 0.75rem;
}

.btn {
    font-weight: 500;
}

.bg-light {
    background-color: rgba(var(--bs-light-rgb), 0.8) !important;
}
</style>
@endsection